version: "3.7"
services:
  fastapi_app:
    build:
      context: fastapi/.
    container_name: fastapi_app
    ports:
      - "8000:8000"
    expose:
      - 8000

  bot:
    build:
      context: bot/.
    container_name: bot
